---
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run lint
            - run: npm test -- --coverage
            - run: npm run build --if-present
            - run: npm audit --omit dev
            - name: Upload coverage
              uses: codecov/codecov-action@v4
              with:
                  files: ./coverage/lcov.info
                  flags: unittests
                  token: ${{ secrets.CODECOV_TOKEN }}
        strategy:
            matrix:
                node-version: [18.x, 20.x]
name: CI
"on":
    pull_request:
        branches: [master]
    push:
        branches: [master]
